### ISSUE TITLE
TakeItem makes FPS down, can it's performance be improved?

### ISSUE THREAD

**Issue by liiijz** [soomla/unity3d-store#493] opened 2015-10-14 18:13 UTC
StoreInventory.TakeItem
VirtualGoodsStorage.Remove
...
These functiosn are not very smooth,
when I called them, you can see the frame count is going down for half a second,
especially when you are doing some animation in the scene, after calling them, the animation will be interrupted not very smooth...

Also in the MuffinRush Example, I notice that when pressing the buy item, the FPS will go to 10 fps, any suggestion on how to improve the performance and code efficiency?

1.8.4 on Unity

**Comment by borisspektor** [comment] 2015-10-15 14:21
Duplicate of http://answers.soom.la/t/some-soomla-functions-slow-down-the-scene-frame-rate/3861
Closing...

**Closed by borisspektor** 2015-10-15 14:21 UTC
